repos:
-   repo: https://github.com/klieret/jekyll-relative-url-check
    rev: v2.0.2
    hooks:
    -   id: jekyll-relative-url-check-html
    -   id: jekyll-relative-url-check-markdown
-   repo: https://github.com/codespell-project/codespell
    rev: 'v2.2.6'
    hooks:
    -   id: codespell
        args: ["-I", "codespell.txt"]
        types_or: ["markdown"]
        exclude: '(organization/_posts/2016/.*)|(organization/_posts/2017/.*)|(organization/_posts/2018/.*)|(organization/_posts/2019/.*)|(organization/_posts/2020/.*)|(organization/_posts/2021/.*)|(organization/_posts/2022/.*)'
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: check-case-conflict

ci:
    autoupdate_schedule: monthly

