repos:
-   repo: https://github.com/klieret/jekyll-relative-url-hook
    rev: 99e0e8dd46b99eb07a646927149482b2f6718207
    hooks:
    -   id: jekyll_relative_url_html
    -   id: jekyll_relative_url_markdown
-   repo: https://github.com/codespell-project/codespell
    rev: 'v2.1.0'
    hooks:
    -   id: codespell
        args: ["-I", "codespell.txt"]
        types_or: ["markdown", "html"]

ci:
    autoupdate_schedule: monthly

