language: ruby
rvm:
- 2.2

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./.travis-scripts/html-proofer

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache: bundler

sudo: false
