title: HEP Software Foundation
description: HEP Software Foundation Website
url: http://www.hepsoftwarefoundation.org
excerpt_separator: <!--more-->
timezone: Europe/Paris
highlighter: rouge
markdown: kramdown
future: true
exclude: [vendor]
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-redirect-from
collections:
  activities:
    output: true
    permalink: /activities/:title.html
  activities-archive:
    output: true
    permalink: /activities-archive/:title.html
  gsocorgs:
    output: true
    permalink: /gsoc/organizations/:path.html
  gsocprojects:
    output: true
    permalink: /gsoc/projects/:path.html
  gsocproposals:
    output: true
    permalink: /gsoc/:path.html
  gsocblogs:
    output: true
    permalink: /gsoc/blogs/:path.html
  gsdocs-orgs:
    output: true
    permalink: /gsdocs/organizations/:path.html
  gsdocs-projects:
    output: true
    permalink: /gsdocs/projects/:path.html
  gsdocs-proposals:
    output: true
    permalink: /gsdocs/:path.html
  gsdocs-blogs:
    output: true
    permalink: /gsdocs/blogs/:path.html
  meetings:
    output: true
    permalink: /meetings/:title.html
  training:
    output: true
    permalink: /training/:path.html
  profiles:
    output: true
    permalink: /profiles/:path.html

defaults:
  - scope:
      path: "_gsocproposals/2026"
    values:
      year: 2026

docs:
  url: https://github.com/HSF/documents/blob/master
  cwp201711: https://github.com/HSF/documents/blob/master/CWP/papers/2017-11
