name: HEP Software Foundation Newsletter
description: News from the HEP Software Foundation
url: http://www.hepsoftwarefoundation.org
excerpt_separator: <!--more-->
timezone: Switzerland/Geneva
highlighter: rouge
markdown: kramdown
future: true
exclude: [vendor]
plugins_dir:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-redirect-from
collections:
  activities:
    output: true
    permalink: /activities/:title.html
  gsocproposals:
    output: true
    permalink: /gsoc/:path.html

docs:
  url: https://github.com/HEP-SF/documents/blob/master
  cwp201711: https://github.com/HEP-SF/documents/blob/master/CWP/papers/2017-11
